# Generated by Django 4.2 on 2025-09-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="is_analyzed_by_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
        migrations.AddField(
            model_name="symptomprediction",
            name="doctor_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="symptomprediction",
            name="doctor_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="symptomprediction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("patient", "Patient"), ("doctor", "Doctor")],
                        default="patient",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("general", "General Practice"),
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("endocrinology", "Endocrinology"),
                            ("gastroenterology", "Gastroenterology"),
                            ("neurology", "Neurology"),
                            ("oncology", "Oncology"),
                            ("orthopedics", "Orthopedics"),
                            ("pediatrics", "Pediatrics"),
                            ("psychiatry", "Psychiatry"),
                            ("pulmonology", "Pulmonology"),
                            ("radiology", "Radiology"),
                            ("urology", "Urology"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("hospital_affiliation", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="symptomprediction",
            name="analyzed_by_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.doctorprofile",
            ),
        ),
    ]
